version: '3'

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpformchallenge
    hostname: phpformchallenge
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - "./html:/var/www/html/"
      - "./ssl/server.key:/etc/ssl/private/server.key"
      - "./ssl/server.crt:/etc/ssl/certs/server.crt"                    
      - "./log/apache2:/var/log/apache2"
      - "./apache_config:/etc/apache2/sites-enabled" 
      - "./:/etc/apache2/apche2.conf"
    networks:
      php-mysql-networks:
        ipv4_address: 192.168.1.150
    depends_on:
      - php-db
    environment:
      - HOSTNAME=192.168.1.150
      - APACHE_SERVER_NAME=phpformchallenge
      - APACHE_LOG_DIR=/var/log/apache2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"] 
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  php-db:
    image: mysql:8.3.0
    container_name: run-php-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "Password"
      MYSQL_DATABASE: "my_form"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "p@55w0rd"
    volumes:
      - "./MySQL/db:/docker-entrypoint-initdb.d"
      - "./log/mysql:/var/log/mysql"
      - mysql-data:/var/lib/mysql
    networks:
      php-mysql-networks:
        ipv4_address: 192.168.1.149
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  php-myadmin:
    container_name: run-php-MyAdmin
    image: phpmyadmin:apache
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      php-mysql-networks:
        ipv4_address: 192.168.1.151
    links:
      - php-db:db
    depends_on:
      - php-db

volumes:
  mysql-data:

networks:
  php-mysql-networks:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
