# Use a PHP + Apache image as the base
FROM php:8-apache

# Install OpenSSL and enable SSL and mod_rewrite
RUN apt-get update && apt-get install -y \
    openssl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Enable SSL and mod_rewrite Apache modules
RUN a2enmod ssl rewrite

# Create directories for SSL certificates
RUN mkdir -p /etc/ssl/private 
RUN mkdir -p /etc/ssl/certs

# Copy SSL certificates from the host (or generated by the script)
COPY ./ssl/server.crt /etc/ssl/certs/server.crt
COPY ./ssl/server.key /etc/ssl/private/server.key

# Configure Apache to handle HTTPS (port 443) and redirect HTTP (port 80) to HTTPS
COPY ./apache_config/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./apache_config/default-ssl.conf /etc/apache2/sites-available/default-ssl.conf

# Enable the SSL site and default SSL config
RUN a2ensite 000-default.conf
RUN a2ensite default-ssl.conf
RUN a2enmod ssl

# Expose HTTP and HTTPS ports
EXPOSE 80 443

# Fallback mechanism to ensure container stays up even if Apache fails
# We run apache2 in the foreground and if it fails, run a shell to keep the container alive.
CMD apache2ctl -D FOREGROUND || tail -f /dev/null
